import { createHash } from "node:crypto";

import { confirmPreferenceProfile, type PreferenceProfileDraft, type PreferenceProfileSnapshot } from "../decision/preference-profile";
import { confirmRelocationProfile, type RelocationProfileDraft, type RelocationProfileSnapshot } from "../decision/relocation-profile";
import type { FormalResidenceVerdict } from "../decision/formal-residence-verdict";
import { rankPlaces, type RankedPlace, type RankablePlace, type RequiredMismatch } from "../decision/place-ranker";
import type { EvidenceIntegrity } from "../research/research-plan";

export interface PlaceFrontierPrepared { readonly runId: string; readonly profileId: string; readonly preferenceProfileId: string; readonly assessmentAt: string; readonly rankingSnapshotId: string; readonly contextHash: string; }
export interface FrontierCountry { readonly countryCode: string; readonly label: string; readonly flag: string; readonly coordinate: { readonly lat: number; readonly lng: number }; }
export interface FrontierMarker { readonly country: FrontierCountry; readonly rank: number; readonly countryCheckRunId: string; readonly sourceAssessmentRulesVersion: string; readonly lastCheckedAt: string; readonly evidenceSnapshotId: string; readonly currentKnowledgeRevisionId?: string; readonly updatedKnowledgeRevisionId?: string; readonly knowledgeUpdatedAt?: string; readonly formalVerdict: FormalResidenceVerdict; }
export interface RankingSnapshot { readonly schemaVersion: "place-ranking@1"; readonly id: string; readonly runId: string; readonly profileSnapshotId: string; readonly preferenceProfileSnapshotId: string; readonly assessmentAt: string; readonly contextHash: string; readonly knowledgeRevisionIds: Readonly<Record<string, string | null>>; readonly ordered: readonly RankedPlace[]; readonly excluded: readonly RequiredMismatch[]; readonly rulesVersion: "place-ranker@1"; readonly createdAt: string; }
export interface ShortlistSnapshot { readonly schemaVersion: "place-shortlist@1"; readonly id: string; readonly runId: string; readonly rankingSnapshotId: string; readonly markers: readonly FrontierMarker[]; readonly rulesVersion: "country-frontier@1"; readonly createdAt: string; }
export interface PlaceFrontierReadModel { readonly runId: string; readonly assessmentAt: string; readonly rankingSnapshot: RankingSnapshot; readonly shortlistSnapshot: ShortlistSnapshot; }
export interface CountryVerifierPort { check(input: { readonly country: RankablePlace; readonly profileId: string; readonly parentRunId: string; readonly emitProgress: (progress: never) => void | Promise<void>; readonly signal: AbortSignal; }): Promise<Omit<FrontierMarker, "country" | "rank" | "formalVerdict"> & { readonly verdict: FormalResidenceVerdict }>; present(input: { readonly parentRunId: string; readonly countryCode: string; readonly countryCheckRunId: string; readonly profileId: string; }): Promise<Omit<FrontierMarker, "country" | "rank" | "countryCheckRunId" | "formalVerdict"> & { readonly verdict: FormalResidenceVerdict }>; }
export interface PlaceFrontierApplicationPorts { readonly profiles: { appendRelocation(snapshot: RelocationProfileSnapshot): Promise<void>; loadRelocationVerified(id: string): Promise<RelocationProfileSnapshot>; appendPreference(snapshot: PreferenceProfileSnapshot): Promise<void>; loadPreferenceVerified(id: string): Promise<PreferenceProfileSnapshot>; }; readonly rankingInputs: { freezeCurrent(): Promise<{ readonly places: readonly RankablePlace[]; readonly knowledgeRevisionIds: Readonly<Record<string, string | null>>; }>; }; readonly rank: typeof rankPlaces; readonly store: { appendRanking(snapshot: RankingSnapshot): Promise<void>; appendShortlist(snapshot: ShortlistSnapshot): Promise<void>; loadRankingVerified(id: string): Promise<RankingSnapshot>; loadShortlistVerified(runId: string): Promise<ShortlistSnapshot>; }; readonly knowledge: { loadVerified(id: string): Promise<{ readonly id: string; readonly countryCode: string }> }; readonly verifier: CountryVerifierPort; readonly integrity: EvidenceIntegrity; readonly clock: () => Date; readonly nextRunId: () => string; }
export interface PlaceFrontierApplication { preparePlaceFrontier(input: { readonly profile: RelocationProfileDraft; readonly preferences: PreferenceProfileDraft } | { readonly profileId: string; readonly preferenceProfileId: string }): Promise<PlaceFrontierPrepared>; runPlaceFrontier(prepared: PlaceFrontierPrepared, emit: (event: PlaceFrontierEvent) => void | Promise<void>, signal: AbortSignal): Promise<PlaceFrontierReadModel>; presentPlaceFrontier(runId: string): Promise<PlaceFrontierReadModel>; }
export type PlaceFrontierEvent = { readonly runId: string; readonly sequence: number; readonly occurredAt: string; readonly type: "ranking_sealed" | "country_activated" | "country_progress" | "country_completed" | "frontier_completed"; readonly payload: unknown; };
function mismatch(): never { throw new Error("integrity_mismatch"); }
export function countryCheckRunId(parentRunId: string, countryCode: string): string { return `frontier-country:${createHash("sha256").update(JSON.stringify({ countryCode, parentRunId })).digest("hex")}`; }
function country(place: RankedPlace): FrontierCountry { return { countryCode: place.countryCode, label: place.label, flag: place.flag, coordinate: { ...place.coordinate } }; }
export function projectTerminalSummary(readModel: PlaceFrontierReadModel) { const nonRed = readModel.shortlistSnapshot.markers.filter((marker) => marker.formalVerdict.marker !== "red"); const green = nonRed.filter((marker) => marker.formalVerdict.marker === "green").length; const yellow = nonRed.length - green; return { countries: nonRed.map((marker) => marker.country.countryCode), composition: { green, yellow }, stopCondition: nonRed.length === 5 ? "five_non_red" as const : "installed_coverage_exhausted" as const, preliminary: yellow > 0 || nonRed.length < 5 }; }
export function createPlaceFrontierApplication(ports: PlaceFrontierApplicationPorts): PlaceFrontierApplication {
  const verifyRankingKnowledge = async (ranking: RankingSnapshot, verifyOwnership: boolean) => { const codes = [...ranking.ordered.map((p) => p.countryCode), ...ranking.excluded.map((p) => p.countryCode)]; if (Object.keys(ranking.knowledgeRevisionIds).sort().join() !== [...codes].sort().join()) mismatch(); if (verifyOwnership) for (const [code, id] of Object.entries(ranking.knowledgeRevisionIds)) if (id !== null && (await ports.knowledge.loadVerified(id)).countryCode !== code) mismatch(); };
  const present = async (runId: string) => { const shortlist = await ports.store.loadShortlistVerified(runId); const ranking = await ports.store.loadRankingVerified(shortlist.rankingSnapshotId); if (ranking.runId !== runId || shortlist.rankingSnapshotId !== ranking.id) mismatch(); await ports.profiles.loadRelocationVerified(ranking.profileSnapshotId); await ports.profiles.loadPreferenceVerified(ranking.preferenceProfileSnapshotId); await verifyRankingKnowledge(ranking, true); for (const marker of shortlist.markers) { const replay = await ports.verifier.present({ parentRunId: runId, countryCode: marker.country.countryCode, countryCheckRunId: marker.countryCheckRunId, profileId: ranking.profileSnapshotId }); const expected = { sourceAssessmentRulesVersion: marker.sourceAssessmentRulesVersion, verdict: marker.formalVerdict, evidenceSnapshotId: marker.evidenceSnapshotId, ...(marker.currentKnowledgeRevisionId === undefined ? {} : { currentKnowledgeRevisionId: marker.currentKnowledgeRevisionId }), ...(marker.updatedKnowledgeRevisionId === undefined ? {} : { updatedKnowledgeRevisionId: marker.updatedKnowledgeRevisionId }), ...(marker.knowledgeUpdatedAt === undefined ? {} : { knowledgeUpdatedAt: marker.knowledgeUpdatedAt }), lastCheckedAt: marker.lastCheckedAt }; if (ports.integrity.canonical(replay) !== ports.integrity.canonical(expected)) mismatch(); } return { runId, assessmentAt: ranking.assessmentAt, rankingSnapshot: ranking, shortlistSnapshot: shortlist }; };
  return Object.freeze({
    async preparePlaceFrontier(input: Parameters<PlaceFrontierApplication["preparePlaceFrontier"]>[0]) { const now = ports.clock(); const profile = "profile" in input ? confirmRelocationProfile(input.profile, () => now) : await ports.profiles.loadRelocationVerified(input.profileId); const preferences = "preferences" in input ? confirmPreferenceProfile(input.preferences, () => now) : await ports.profiles.loadPreferenceVerified(input.preferenceProfileId); if ("profile" in input) await ports.profiles.appendRelocation(profile); if ("preferences" in input) await ports.profiles.appendPreference(preferences); const runId = ports.nextRunId(); const assessmentAt = now.toISOString(); const inputs = await ports.rankingInputs.freezeCurrent(); const result = ports.rank({ assessmentAt: assessmentAt.slice(0, 10), preferences, places: inputs.places }); const rankingSnapshotId = `${runId}:ranking`; const contextHash = ports.integrity.hash(ports.integrity.canonical({ runId, profileId: profile.id, preferenceProfileId: preferences.id, assessmentAt, rankingSnapshotId })); const snapshot: RankingSnapshot = { schemaVersion: "place-ranking@1", id: rankingSnapshotId, runId, profileSnapshotId: profile.id, preferenceProfileSnapshotId: preferences.id, assessmentAt, contextHash, knowledgeRevisionIds: inputs.knowledgeRevisionIds, ordered: result.ordered, excluded: result.excluded, rulesVersion: result.rulesVersion, createdAt: assessmentAt }; await verifyRankingKnowledge(snapshot, false); await ports.store.appendRanking(snapshot); return { runId, profileId: profile.id, preferenceProfileId: preferences.id, assessmentAt, rankingSnapshotId, contextHash }; },
    async runPlaceFrontier(prepared: PlaceFrontierPrepared, emit: (event: PlaceFrontierEvent) => void | Promise<void>, signal: AbortSignal) { if (signal.aborted) throw signal.reason; const ranking = await ports.store.loadRankingVerified(prepared.rankingSnapshotId); if (ranking.runId !== prepared.runId || ranking.profileSnapshotId !== prepared.profileId || ranking.preferenceProfileSnapshotId !== prepared.preferenceProfileId || ranking.contextHash !== prepared.contextHash) mismatch(); await ports.profiles.loadRelocationVerified(prepared.profileId); await ports.profiles.loadPreferenceVerified(prepared.preferenceProfileId); await verifyRankingKnowledge(ranking, false); let sequence = 0; const send = async (type: PlaceFrontierEvent["type"], payload: unknown) => emit({ runId: prepared.runId, sequence: ++sequence, occurredAt: ports.clock().toISOString(), type, payload }); await send("ranking_sealed", { rankingSnapshotId: ranking.id, orderedCountryCodes: ranking.ordered.map((p) => p.countryCode), excludedCountryCodes: ranking.excluded.map((p) => p.countryCode) }); const activated = ranking.ordered.slice(0, 5); let checkIndex = 0; let nextIndex = activated.length; const markers: FrontierMarker[] = []; for (const place of activated) await send("country_activated", { country: country(place), rank: place.rank }); while (checkIndex < activated.length) { if (signal.aborted) throw signal.reason; const place = activated[checkIndex++]!; const checked = await ports.verifier.check({ country: place, profileId: prepared.profileId, parentRunId: prepared.runId, emitProgress: async () => undefined, signal }); const { verdict, ...checkMetadata } = checked; const marker: FrontierMarker = { ...checkMetadata, formalVerdict: verdict, country: country(place), rank: place.rank }; if (marker.countryCheckRunId !== countryCheckRunId(prepared.runId, place.countryCode)) mismatch(); markers.push(marker); await send("country_completed", { marker }); if (marker.formalVerdict.marker === "red" && nextIndex < ranking.ordered.length) { const replacement = ranking.ordered[nextIndex++]!; activated.push(replacement); await send("country_activated", { country: country(replacement), rank: replacement.rank }); } if (markers.filter((m) => m.formalVerdict.marker !== "red").length === 5) break; } if (markers.filter((m) => m.formalVerdict.marker !== "red").length !== 5 && markers.length !== ranking.ordered.length) mismatch(); const shortlist: ShortlistSnapshot = { schemaVersion: "place-shortlist@1", id: `${prepared.runId}:shortlist`, runId: prepared.runId, rankingSnapshotId: ranking.id, markers, rulesVersion: "country-frontier@1", createdAt: ports.clock().toISOString() }; await ports.store.appendShortlist(shortlist); const readModel = { runId: prepared.runId, assessmentAt: ranking.assessmentAt, rankingSnapshot: ranking, shortlistSnapshot: shortlist }; await send("frontier_completed", { readModel }); return readModel; },
    presentPlaceFrontier: present,
  });
}
